➤ Executing task [32mdeploy:prepare[39m
↳ on [prod]

[33mIn PhpSecLib.php line 99:[39m
[37;41m                                                  [39;49m
[37;41m  [RuntimeException]                              [39;49m
[37;41m  Unable to login with the provided credentials.  [39;49m
[37;41m                                                  [39;49m

[33mException trace:[39m
  at [32m/home/fendy/coding/kanaya-admin/vendor/deployer/deployer/src/Server/Remote/PhpSecLib.php:99[39m
 Deployer\Server\Remote\PhpSecLib->connect() at [32m/home/fendy/coding/kanaya-admin/vendor/deployer/deployer/recipe/common.php:105[39m
 {closure}() at [32mn/a:n/a[39m
 call_user_func() at [32m/home/fendy/coding/kanaya-admin/vendor/deployer/deployer/src/Task/Task.php:79[39m
 Deployer\Task\Task->run() at [32m/home/fendy/coding/kanaya-admin/vendor/deployer/deployer/src/Executor/SeriesExecutor.php:43[39m
 Deployer\Executor\SeriesExecutor->run() at [32m/home/fendy/coding/kanaya-admin/vendor/deployer/deployer/src/Console/TaskCommand.php:82[39m
 Deployer\Console\TaskCommand->execute() at [32m/home/fendy/coding/kanaya-admin/vendor/symfony/console/Command/Command.php:255[39m
 Symfony\Component\Console\Command\Command->run() at [32m/home/fendy/coding/kanaya-admin/vendor/symfony/console/Application.php:987[39m
 Symfony\Component\Console\Application->doRunCommand() at [32m/home/fendy/coding/kanaya-admin/vendor/symfony/console/Application.php:255[39m
 Symfony\Component\Console\Application->doRun() at [32m/home/fendy/coding/kanaya-admin/vendor/symfony/console/Application.php:148[39m
 Symfony\Component\Console\Application->run() at [32m/home/fendy/coding/kanaya-admin/vendor/deployer/deployer/src/Deployer.php:101[39m
 Deployer\Deployer->run() at [32m/home/fendy/coding/kanaya-admin/vendor/deployer/deployer/bin/dep:64[39m

[32mdeploy [-p|--parallel][39m

